# Generated by Django 6.0.3 on 2026-03-16 21:30

import auth.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'custom user', 'verbose_name_plural': 'custom users'},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', auth.managers.CustomUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
